### PR TITLE
fix: image not found in README.md while mdbook build

### LINKED ISSUE #115: Markdown images break the plugin invoking errors
For example:

```
![FXRMotionControllerData Blueprint representation](fxrmotioncontrollerdata-blueprint-representation.png "FXRMotionControllerData Blueprint representation")
```

Produces:

```
2024-07-18 14:00:54 [INFO] (mdbook::book): Book building has started
2024-07-18 14:00:55 [INFO] (mdbook::book): Running the epub backend
2024-07-18 14:00:55 [INFO] (mdbook::renderer): Invoking the "epub" renderer
Running mdbook-epub as plugin...
[2024-07-18T12:00:55Z ERROR mdbook_epub::generator] Failed finding/fetch resource taken from content? Look up content for possible error... Caused by: Asset was not found: 'fxrmotioncontrollerdata-blueprint-representation.png' by '/SomeProject/Handbook/src/advanced-topics/openxr/consuming-fxrmotioncontrollerdata/index.md/fxrmotioncontrollerdata-blueprint-representation.png', error = No such file or directory (os error 2)
[2024-07-18T12:00:55Z ERROR mdbook_epub] Asset was not found: 'fxrmotioncontrollerdata-blueprint-representation.png' by '/SomeProject/Handbook/src/advanced-topics/openxr/consuming-fxrmotioncontrollerdata/index.md/fxrmotioncontrollerdata-blueprint-representation.png', error = No such file or directory (os error 2)
2024-07-18 14:00:55 [ERROR] (mdbook::renderer): Renderer exited with non-zero return code.
2024-07-18 14:00:55 [ERROR] (mdbook::utils): Error: Rendering failed
2024-07-18 14:00:55 [ERROR] (mdbook::utils): 	Caused By: The "epub" renderer failed
make: *** [GNUmakefile:282: serve] Error 101
```

This however works fine with the HTML backend as intended.

### PR DESCRIPTION
**Pull request by dieterplex**
Fix #115

- Adjust the root of `README.md` chapter when running as a preprocessor and links preprocessor enabled
- Referenced image is not showed due to resources added to wrong path

### CODE REVIEW

File: src/resources/resource.rs [hunk 1]
```diff
@@ -48,9 +48,15 @@ pub(crate) fn find(ctx: &RenderContext) -> Result<HashMap<String, Asset>, Error>
                     continue;
                 }
                 for link in find_assets_in_markdown(&ch.content)? {
-                    let asset = match Url::parse(&link) {
-                        Ok(url) => Asset::from_url(url, &ctx.destination),
-                        Err(_) => Asset::from_local(&link, &src_dir, ch.path.as_ref().unwrap()),
```
Comment (dieterplex) [inline src/resources/resource.rs:53]: I was a bit of surprise that test `find_local_asset` got pass and ignore assets outside source directory silently.

File: src/resources/resource.rs [hunk 2]
```diff
@@ -48,9 +48,15 @@ pub(crate) fn find(ctx: &RenderContext) -> Result<HashMap<String, Asset>, Error>
...
+                    let asset = if let Ok(url) = Url::parse(&link) {
+                        Asset::from_url(url, &ctx.destination)
+                    } else {
+                        let result = Asset::from_local(&link, &src_dir, ch.path.as_ref().unwrap());
+                        if let Err(Error::AssetOutsideSrcDir(_)) = result {
+                            warn!("Asset '{link}' is outside source dir '{src_dir:?}' and ignored");
+                            continue;
+                        };
```
Comment (dieterplex) [inline src/resources/resource.rs:58]: I was a bit of surprise that test find_local_asset got pass and ignore assets outside source directory silently.

File: src/resources/asset.rs [hunk 3]
```diff
@@ -82,14 +82,7 @@ impl Asset {
             return Err(Error::AssetFile(absolute_location));
         }
         // Use filename as embedded file path with content from absolute_location.
-        let binding = utils::normalize_path(Path::new(link));
-        debug!("Extracting file name from = {:?}, binding = '{binding:?}'", &full_filename.display());
-        let filename = if cfg!(target_os = "windows") {
-            binding.as_os_str().to_os_string()
-                .into_string().expect("Error getting filename for Local Asset").replace('\\', "/")
```
Comment (blandger) [inline src/resources/asset.rs:89]: I'm not sure if that is good to remove that code. I remember there were problems on Win, so I added that piece of code. I doubt that is good.

File: src/resources/resource.rs (hunk 2 above)
Comment (blandger) [reply src/resources/resource.rs:58]: > outside source directory silently before from here.

Yes, we want to create book finally and some 'missing' images are not a big problem.

File: src/resources/asset.rs (hunk 3 above)
Comment (dieterplex) [reply src/resources/asset.rs:89]: Any exact cases could be added testcases?

Things like https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file?

File: src/resources/resource.rs (hunk 2 above)
Comment (dieterplex) [reply src/resources/resource.rs:58]: I do like it more explicit instead of silently ignored, so user could react accordingly.

File: src/resources/asset.rs (hunk 3 above)
Comment (blandger) [reply src/resources/asset.rs:89]: That code is related to problem of building epub book on Windows platform. We should change window's based '\\' to path like '/' as that should be by epub specification.

See also 
`#[test] fn test_normalize_path_win() {`

https://github.com/Michael-F-Bryan/mdbook-epub/issues/11

Comment (dieterplex) [reply src/resources/asset.rs:89]: I think epub-builder already do its best [here to not use backspaces in zip files](https://github.com/crowdagger/epub-builder/blob/56a783e3826fb0a0d335d5a5070e398ecfb5072a/src/zip_library.rs#L62-L63) to conform ePub spec. And I check the book generated with this PR works fine with calibre ebook-viewer that images are embeded and displayed without error.
We need to normalize but not canonicalize the path causing issue. So just using `strip_prefix` is enough.

Comment (dieterplex) [reply src/resources/asset.rs:89]: BTW, the `link` parsed by pulldown-cmark here should be a valid [link text](https://spec.commonmark.org/0.30/#images) according to [CommonMark Spec](https://commonmark.org/). It's wrong to accept a backslash-separated path or test it since pulldown-cmark crate is a pull parser for [CommonMark](http://commonmark.org/).

Comment (dieterplex) [reply src/resources/asset.rs:89]: `binding` may give wrong path to add assets to zip. Consider the link in test cases at L98, `../upper/assets/asset1.jpg`, is the image added to zip with `upper/assets/asset1.jpg`?

Comment (dieterplex) [reply src/resources/asset.rs:89]: About normalizing path, we could use `normpath` instead [like mdbook-pandoc does](https://github.com/max-heller/mdbook-pandoc/commit/319c7bab) later.

Comment (blandger) [reply src/resources/asset.rs:89]: ok, convinced about that. I tested on Win11 looks like you are correct but....
I found one issue that works fine on Linux, but doesn't on Win.
See explanation below.

File: tests/dummy/src/02_advanced/README.md [hunk 4]
```diff
@@ -0,0 +1,5 @@
+# README.md tests
+
+## image link
+
+![Awesome image in the same folder](Epub_logo.svg "Awesome")
```
Comment (blandger) [inline tests/dummy/src/02_advanced/README.md:5]: Let's add following image link to that page.

```
![Awesome image in the same folder](Epub_logo.svg "Awesome")

![Awesome image 2 in the another folder](..\\reddit.svg)

![Awesome image 3 in the another folder](..\\assets\\rust-logo.png)

```

I've found that page renders correctly on Linux, but wrong on Win11. Images are not shown due to incorrect paths on Win. Can you check and confirm that ?

Comment (blandger) [reply tests/dummy/src/02_advanced/README.md:5]: I've replalced all / by \\ in all pages for testing on Win.

Comment (blandger) [reply tests/dummy/src/02_advanced/README.md:5]: That can be related to issue - https://github.com/Michael-F-Bryan/mdbook-epub/issues/126 but we need support for both cases.
